import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@components/providers";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Study Log",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-[100vh] select-none flex flex-col min-w-[1200px]`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
