name: Dockerizing to Amazon ECR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: study-log
  ECR_REGISTRY: 214925768882.dkr.ecr.ap-northeast-2.amazonaws.com

jobs:
  ci:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login To Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create .env file from secrets
        run: |
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./server/Dockerfile.prod ./server
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Save image tag to file
        run: echo "${IMAGE_TAG}" > image-tag.txt

      - name: Verify image tag file
        run: cat image-tag.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: image-tag
          path: image-tag.txt

  cd:
    name: Deploy Docker Image to Server
    runs-on: [self-hosted, study-log-server]
    needs: ci
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image-tag

      - name: Read image tag
        id: read-image-tag
        run: |
          IMAGE_TAG=$(cat image-tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull image from Amazon ECR and restart container
        run: |
          docker pull ${{ env.IMAGE_TAG }}
          docker stop test_con || true && docker rm test_con || true
          docker run -d --name test_con -p 80:80 --restart unless-stopped ${{ env.IMAGE_TAG }}
