export const languageMapper = {
  js: "JavaScript",
  jsx: "JavaScript",
  ts: "TypeScript",
  tsx: "TypeScript",
  ipynb: "Python",
  py: "Python",
  java: "Java",
  kt: "Kotlin",
  swift: "Swift",
  go: "Go",
  rb: "Ruby",
  php: "Php",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  sql: "SQL",
  shell: "Shell",
  sh: "Shell",
  json: "json",
  geojson: "json",
  xml: "xml",
  yml: "yaml",
  yaml: "yaml",
  md: "markdown",
  txt: "text",
  other: "other",
};
